# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_auto_20170720_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
