# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 00:13
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

def forwards(apps, schema_editor):
    Sound = apps.get_model('sounds', 'Sound')
    Soundbox = apps.get_model('sounds', 'Soundbox')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    for user in User.objects.all():
        default_box = Soundbox.objects.create(user=user, title='Default', description='Default description.')
        default_box.save()
        for sound in user.sound_set.all():
            sound.soundbox = default_box
            sound.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0006_sound_soundbox'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
