# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0008_auto_20170725_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='user',
        ),
    ]
